name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: self-hosted
    env:
      KUBECONFIG: C:\Users\user\.kube\config
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Git Bash instead of WSL bash
        shell: powershell
        run: Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files\Git\bin"

      - name: Build Docker image
        run: docker build -t snip .

      - name: Load image into kind cluster
        run: kind load docker-image snip --name prview

      - name: Debug kubectl context
        shell: bash
        run: |
          which bash
          kubectl config current-context
          kubectl get nodes

      - name: Create preview environment
        shell: bash
        run: |
          sed -i 's/\r$//' scripts/create-preview.sh
          bash scripts/create-preview.sh ${{ github.event.pull_request.number }}